### ISSUE TITLE
Does not capture in FHD if monitor is not the same resolution

### ISSUE THREAD

**Issue by McRayJason** [adainrivers/nw-tradingpost-price-extractor#1]
Hello, first of all, then you very much for the work on gmaing.tools and this data extractor. It is going to help a lot when leveling up the crafting.

Now for the issue,
I do have a game set to 1920x1080 but when i click on capture (or press F11) it gives me an error
![image](https://user-images.githubusercontent.com/39248367/140543363-b3a1a639-9e14-48d8-8502-f2ebf7b4d4eb.png)
It appears that i need to change the monitor resolution as well, and not only the game, then it works fine.

I am attaching the screens in different resolutions for you:
1920x1080 (with monitor set to 2560x1440)
![image](https://user-images.githubusercontent.com/39248367/140543553-97acab4c-868b-47d4-ad86-0f404d606534.png)

2560x1440 (with monitor the same res)
![image](https://user-images.githubusercontent.com/39248367/140544074-ab2c8ed6-b85d-4399-b9bb-5101aaaf49ab.png)

**Comment by adainrivers** [comment]
Also added support for (hopefully) all full-screen resolutions with this release: 

https://github.com/adainrivers/nw-tradingpost-price-extractor/releases/tag/0.1.0

**Comment by McRayJason** [comment]
Hi it now works nicely with different resolutions (also when system resolution is different than in-game). Tho the #2 is still a problem.
