### ISSUE TITLE
Wyrdwood does not get recognized

### ISSUE THREAD

**Issue by geraldbaeck** [adainrivers/nw-tradingpost-price-extractor#10]
![wyrdwood](https://user-images.githubusercontent.com/199418/141680640-3e63148d-5201-463c-99cd-bb05e94d60e8.png)

**Comment by adainrivers** [comment]
Could you please provide a proper screenshot for it, you can do so by pressing F12 (default screenshot key for steam). This one doesn't work at all because of the extra black area at the bottom.

Thank you for the report.
