### ISSUE TITLE
Add command line interface please

### ISSUE THREAD

**Issue by IMelker** [adainrivers/nw-tradingpost-price-extractor#11]
Please add cli interface to enable app ussage as an external tool.

Something like:
./app.exe --config=./config.json --output=./out.json --img=img1.jpg --img=img2.jpg

**Comment by jafreli** [comment]
I think something like that would be very cool.
Maybe it is possible that you can also transfer entire folders with images.

**Comment by adainrivers** [comment]
Sorry, the tool is no longer under active development, so I won't be adding these features.
