### ISSUE TITLE
Request for advice on optimizing results

### ISSUE THREAD

**Issue by svange** [adainrivers/nw-tradingpost-price-extractor#13]
Hi! Thanks for sharing. Not looking to ask you to debug or anything, just looking for insight as to what I can do to optimize my results. Here is what I'm getting:

This is a screenshot from the market:
![image](https://user-images.githubusercontent.com/7166607/149668622-795b9ab4-da91-4329-9b5a-26e988e072ac.png)

These are two screenshots of the tool and it's results (2 so I can scroll over and show that the first entry is in fact the first entry on the screenshot from the game.

![image](https://user-images.githubusercontent.com/7166607/149668683-eae6ec47-c2d0-4105-808f-022f4239a3c0.png)

![image](https://user-images.githubusercontent.com/7166607/149668674-4736e060-b1d4-46ba-abbf-b965c14c0e8d.png)

Here are my config.json settings:
{"WindowState":0,"WindowLocation":"242, 161","GameUILanguage":"English","Size":"594, 390","UploadToServer":false,"Region":"US West","Server":"Ashok Vatika"}

I've also tried modifying them to :
{"WindowState":0,"WindowLocation":"242, 161","GameUILanguage":"English","Size":"1920, 1080","UploadToServer":false,"Region":"US West","Server":"Lintukoto"}

(note: the only real difference is the value of the Size parameter)

My monitor resolution is 1920x1080 and I play the game at 1920x1080 (windowed mode).

Any advice to stop getting those weird results seen in picture 1?

Thank you for even considering responding to my question :)

**Comment by adainrivers** [comment]
Hello, it could be because the windowed mode, could you please try with full screen mode?

**Comment by svange** [comment]
Hey, thanks so much for responding :)

I'll give it a shot tonight!
