### ISSUE TITLE
Wrong detected prices

### ISSUE THREAD

**Issue by McRayJason** [adainrivers/nw-tradingpost-price-extractor#2]
When i scan the page, it detects wrong prices.
Screenshot (taken at 1920x1080 (boith monitor and ingame res):
![image](https://user-images.githubusercontent.com/39248367/140546469-3202ccc7-c53b-438a-9ac7-1a908719680c.png)

Detected prices:
https://pastebin.com/ucnYNFnF

Imported prices (even the imported prices from the JSON file are quite off):
![image](https://user-images.githubusercontent.com/39248367/140546421-115d43e7-a6ee-4fef-8332-77a3228b9153.png)

I do understand that reading the screenshot and turning it into text with OCR can be bit problematic, but i do hope you can figure stuff out. If you will need help with testing, hit me up

**Comment by McRayJason** [comment]
Also https://pastebin.com/MQs6qgdN is the debug file if needed

**Comment by adainrivers** [comment]
Hi @McRayJason ,

Thank you for the feedback, could you please try the new release please?

https://github.com/adainrivers/nw-tradingpost-price-extractor/releases/tag/0.1.0

Thanks.

**Comment by McRayJason** [comment]
Import is still not correct.
It looks like the parse is ignoring the "0." if the price is lower than 0.
![image](https://user-images.githubusercontent.com/39248367/140612040-a0dc465c-aec9-4f4e-b58e-5f02c255c716.png)

So the parsed price instead of 0.20 coins is becoming 20 coins

**Comment by adainrivers** [comment]
OCR seems to be accurate, it could be related with the CultureInfo, I'll try to replicate it.

**Comment by adainrivers** [comment]
Could you please give this one a try:
https://github.com/adainrivers/nw-tradingpost-price-extractor/releases/tag/0.1.2

**Comment by McRayJason** [comment]
Awesome. It looks like it works now just fine
![image](https://user-images.githubusercontent.com/39248367/140625639-0513e658-79fa-4ec4-b44a-e1aef5bf6781.png)

The imported parse on gaming.tools is 0.36

**Comment by adainrivers** [comment]
Good to hear, but what I've noticed is that it took 26 seconds for you, that looks very slow.

**Comment by McRayJason** [comment]
Now that you mention it yea, it goes slower than before.

**Comment by adainrivers** [comment]
For me it averages around 1 second, I'll add more detailed logging to the next versiom, then maybe you can send me your logs and we can see where the problem is.

**Comment by adainrivers** [comment]
There are some performance improvements with the latest version if you wanna give it a try.

**Comment by McRayJason** [comment]
I tested the latest version and the parsing is much faster now. Around 1s now.

**Comment by adainrivers** [comment]
Awesome, thank you again for the feedback.
