### ISSUE TITLE
Feature Request: Export Language, ResetOnExport

### ISSUE THREAD

**Issue by puschie286** [adainrivers/nw-tradingpost-price-extractor#4]
Hi, would be nice if you could add another dropdown for the "ExportLanguage" - currently it use the same language as GameUILanguage but most tools only accept english item names.

Another option would be "ResetOnExport" - if you forgot to scan a specific resource / item you need to scan all things again ( most tools reset all prices on import and override only resources / items found in the json )

**Comment by adainrivers** [comment]
Good suggestions, I will add them, thank you.

**Comment by adainrivers** [comment]
Sorry, the tool is no longer under active development, so I won't be adding these features.
