### ISSUE TITLE
Feature Request: Location + Date

### ISSUE THREAD

**Issue by Michii13** [adainrivers/nw-tradingpost-price-extractor#5]
Could you add the Tradingpost location with the date of the export to the json so we would get like data trends

**Comment by Michii13** [comment]
Also maybe the page number of the market if your scanning multiple pages

**Comment by adainrivers** [comment]
What do you mean by the trading post location?

**Comment by Michii13** [comment]
> What do you mean by the trading post location?

The exact city to track market volume of each Outpost

**Comment by adainrivers** [comment]
Sure, can do that. What about the page number, not sure how I can add that to the exported json?

**Comment by ItsCEED** [comment]
I literally came to request this!
This will be insane to see!

**Comment by OverKill-Solutions** [comment]
A timestamp for a historical data chart would be lovely. Though I am not familiar with C# so I'm not much help unfortunately. I have to give props though, this is one of the most un-intrusive ways you could scrape AH data from a game. Will definitely be following this repo!

**Comment by adainrivers** [comment]
Hi guys, here you go:

https://github.com/adainrivers/nw-tradingpost-price-extractor/releases/tag/0.1.8

I won't add the page number, since it doesn't make much sense to add it to the exported data.
