### ISSUE TITLE
"Gamma" is not a New World setting. OCR is bad. App is nonfunctional.

### ISSUE THREAD

**Issue by exo-pla-net** [adainrivers/nw-tradingpost-price-extractor#6]
The docs suggest that we increase gamma:

`readme.md > "How to use" > "Optionally, increase the New World Gamma setting to maximum for better detection rate."`

However, there is no such setting.

Running the OCR on the trading post for Fibers with default visual settings failed to detect any data; "Raw Results" remained empty.

Pushing the game's contrast to maximum, and performing the same test, extracted some data. However, the data was errant; it wasn't detecting all of the 1's. So the data was malformed and useless.

Adjusting the game's brightness up or down caused the OCR to fail to detect any data.

Thus, using the latest version as of 11/12/2021, as cloned and compiled, the app is nonfunctional.

**Comment by exo-pla-net** [comment]
This "processed-image.png", for example, extracted no data:
![processed-image](https://user-images.githubusercontent.com/47930742/141531200-3cf6578c-67c0-4811-b509-8b0c969eae98.png)

**Comment by adainrivers** [comment]
Hi, fixed the Gamma word in README, it's indeed contrast.

Could you send some screenshots of your trading post so I can test. 

Thanks.

**Comment by adainrivers** [comment]
It's not functioning for you, doesn't mean it's not functional. :)
