### ISSUE TITLE
Parsed results aren't matching with the in-game prices

### ISSUE THREAD

**Issue by tcrouch199205** [adainrivers/nw-tradingpost-price-extractor#7]
Some of my prices aren't matching up properly. For instance, I'm searching Cut Sapphire, which has a price of 11.50, but it is parsing as 1.50. It seems to have an issue detecting 11's, as it correctly parses numbers that aren't 11.

**Comment by exo-pla-net** [comment]
Same.

**Comment by adainrivers** [comment]
Hi guys, thank you for the feedback. The OCR quality depends on video settings you are using, for example, lower resolutions might affect the accuracy of the results. It would be nice if you can send me some screenshots so I can test and see what's wrong with your case, you can do it here or in the discord #trading-post-screenshots channel.

https://discord.gg/6CDf4MTd6f

**Comment by adainrivers** [comment]
Unfortunately I can't fix this one without changing the OCR settings, but then all the other images in my test suite starts failing, which seems to be optimal for most of the users. What I can suggest as a short term solution is to play with your game's video settings to find a way that works with the tool.
